version: "3.9"

services:
  backend:
    image: susheelthapaa/task-backend:latest
    container_name: backend_green
    environment:
      - PORT=5000
    ports:
      - "5001:5000"
    restart: always

  frontend:
    image: susheelthapaa/task-frontend:latest
    container_name: frontend_green
    ports:
      - "3001:80"
    restart: always
