version: "3.9"

services:
  backend:
    image: susheelthapaa/task-backend:latest
    container_name: backend_blue
    environment:
      - PORT=5000
    ports:
      - "5000:5000"
    restart: always

  frontend:
    image: susheelthapaa/task-frontend:latest
    container_name: frontend_blue
    ports:
      - "3000:80"
    restart: always
